### ISSUE TITLE
这个只能识别中文吗？

### ISSUE THREAD

**Issue by rkshuai** [novioleo/crnn.mxnet#10]
楼主你好，请问这个只能识别中文吗？

**Comment by novioleo** [comment]
原则上来说非阿拉伯语的文字都能训练。但是我目前只试验了数字额英文和中文。

**Comment by kli-nlpr** [comment]
识别中文的模型有没有可以下载的？thx

**Comment by novioleo** [comment]
唔，我的模型你不一定好用。而且参数也不一致。不过我还是传一份吧，你有需要你就下。

链接：https://pan.baidu.com/s/1jJKAyN0 密码：0z42

seq_len 68
num_label 30
num_hidden 128
num_lstm_layer 2
图片宽度 550
图片高度 32
RGB图，白色背景。

**Comment by kli-nlpr** [comment]
@novioleo  我想知道 这个 seq_len的设计原则是什么？ 谢谢

**Comment by novioleo** [comment]
@kli-nlpr 首先是seq_len能被最后一层卷积层能够整除，这是第一基础，第二就是seq_len最好是num_label的两倍左右，效果很好。
卷积层的最后一层的大小只与图片宽度相关。
