### ISSUE TITLE
批量预测

### ISSUE THREAD

**Issue by youngYMR** [novioleo/crnn.mxnet#13]
请问一下，模型批量预测有说明文档吗？

**Comment by novioleo** [comment]
批量预测就是batchsize改一下就行了。

**Comment by zhyj3038** [comment]
@novioleo   你好，我在mxnet1.2上，训练和测试各种不可以跑啊！ 预测的时候报错，mxnet.base.MXNetError: Failed loading Op warpctc0 of type WarpCTC: [17:49:48] C:\projects\mxnet-distro-win\mxnet-build\3rdparty\nnvm\src\core\op.cc:55: Check failed: op != nullptr Operator WarpCTC is not registered

训练的时候，报错module 'mxnet.symbol' has no attribute WarpCTC

**Comment by novioleo** [comment]
@zhyj3038  #4 看这。

**Comment by novioleo** [comment]
如果没有啥问题，我就关了～

**Comment by youngYMR** [comment]
好的，谢谢作者。






在 2018-07-13 10:25:34，"Tao Luo" <notifications@github.com> 写道：


如果没有啥问题，我就关了～
