### ISSUE TITLE
Test Image on C++ Invoker main.cpp file

### ISSUE THREAD

**Issue by Israrulhaq190** [novioleo/crnn.mxnet#15]
I am trying to test the cpp version using main.cpp file but i am unable to understand how to read file 
in bytes as const std::vector<uchar> so that i can pass it to predict function in predictor class.

Please help this is the main function i am using. 

```
int main(int argc, char** argv) {
    predictor obj = predictor(argv[2],argv[3]);
   // read image here in bytes format
    try {
        std::string result = obj.predict(image);
    }catch(std::exception& e){
        std::cout<<e.what()<<std::endl;
    }
 return 0;
}
```

and this is my prediction function prototype

`std::string predict(const std::vector<uchar> &byte_data);` 

if above things are unclear i can try to explain again. thank you very much.

**Comment by novioleo** [comment]
@Israrulhaq190 https://github.com/novioleo/crnn.mxnet/blob/master/cpp_invoker/main.cpp#L15-L56，please use the bufferfile to load image.

**Comment by Israrulhaq190** [comment]
> @Israrulhaq190 [https://github.com/novioleo/crnn.mxnet/blob/master/cpp_invoker/main.cpp#L15-L56，please](https://github.com/novioleo/crnn.mxnet/blob/master/cpp_invoker/main.cpp#L15-L56%EF%BC%8Cplease) use the bufferfile to load image.

Thanks for quick reply. is it something like this ?


```
int main(int argc, char** argv) {

    BufferFile buf = BufferFile(argv[1]);
    
    predictor obj = predictor(argv[2],argv[3]);
    try {
        std::string result = obj.predict(buf.GetBuffer());
    }catch(std::exception& e){
        std::cout<<e.what()<<std::endl;
    }
 return 0;
}
```

**Comment by novioleo** [comment]
@Israrulhaq190 try it first



------------------ 原始邮件 ------------------
发件人: "israrulhaq"<notifications@github.com>; 
发送时间: 2019年10月15日(星期二) 下午5:50
收件人: "novioleo/crnn.mxnet"<crnn.mxnet@noreply.github.com>; 
抄送: "北国枫叶。"<744351893@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [novioleo/crnn.mxnet] Test Image on C++ Invoker main.cpp file(#15)



 
@Israrulhaq190 https://github.com/novioleo/crnn.mxnet/blob/master/cpp_invoker/main.cpp#L15-L56，please use the bufferfile to load image.
  
Thanks for quick reply. is it something like this ?
 int main(int argc, char** argv) {     BufferFile buf = BufferFile(argv[1]);          predictor obj = predictor(argv[2],argv[3]);     try {         std::string result = obj.predict(buf.GetBuffer());     }catch(std::exception& e){         std::cout<<e.what()<<std::endl;     }  return 0; }

**Comment by Israrulhaq190** [comment]
This is what i am getting. i think return type of getbuffer() is different then input type of predict funciton i.e const std::vector<unsigned char>&


```
detect.cpp: In function ‘int main(int, char**)’:
detect.cpp:182:57: error: no matching function for call to ‘predictor::predict(char*)’
         std::string result = obj.predict(buf.GetBuffer());
                                                         ^
detect.cpp:105:17: note: candidate: std::__cxx11::string predictor::predict(const std::vector<unsigned char>&)
     std::string predict(const std::vector<uchar> &byte_data) {
                 ^~~~~~~
detect.cpp:105:17: note:   no known conversion for argument 1 from ‘char*’ to ‘const std::vector<unsigned char>&’
```

**Comment by novioleo** [comment]
@Israrulhaq190 the main function of the bottom of the `run.cpp` have use to the predict,you can compile the run.cpp instead of use the `main.cpp`.

**Comment by Israrulhaq190** [comment]
> @Israrulhaq190 the main function of the bottom of the `run.cpp` have use to the predict,you can compile the run.cpp instead of use the `main.cpp`.
When i test run.cpp using this command:

When i test run.cpp usng below command:

`g++ run.cpp -o run  /home/israr/Pictures/crnn.mxnet/cpp_invoker/src/test_image.jpg /home/israr/Pictures/crnn.mxnet/model/digit-symbol.json /home/israr/Pictures/crnn.mxnet/model/digit-0000.params /home/israr/Pictures/crnn.mxnet/cpp_invoker/src/trained_classifierNM1.xml 
`
it says

```
/home/israr/Pictures/crnn.mxnet/cpp_invoker/src/test_image.jpg: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status

```

**Comment by Israrulhaq190** [comment]
> @Israrulhaq190 the main function of the bottom of the `run.cpp` have use to the predict,you can compile the run.cpp instead of use the `main.cpp`.

what's the difference between main.cpp and run.cpp ?

I have seen ANDROID & LINUX mentioned in run.cpp. could you please explain ?

**Comment by novioleo** [comment]
i think your compile script is wrong...
why you compile the cpp with the jpg???

**Comment by novioleo** [comment]
@Israrulhaq190 
the run.cpp used for compile a executable program or share object for linux and android....
the main.cpp is pure without main function...

**Comment by Israrulhaq190** [comment]
thanks for explanation. can i use only main.cpp with it's own main function ?

I tried to create the main function as you can see in above thread but there are return type issue for
input predict function.

**Comment by Israrulhaq190** [comment]
> i think your compile script is wrong...
> why you compile the cpp with the jpg???


actually i am passing command line arguments for image_file and model files as you can see in the below main function in run.cpp

```
int main(int args,char* argv[]){
    cv::Mat image = cv::imread(argv[1]);
    m_predictor.init(argv[2],argv[3],argv[4]);
    try {
        std::string result = m_predictor.predict(image);
    }catch(std::exception& e){
#ifdef LINUX
        std::cout<<e.what()<<std::endl;
#endif
#ifdef ANDROID
        LOGE("%s",e.what());    
#endif
    }
}

```

**Comment by novioleo** [comment]
@Israrulhaq190 can you compile the run.cpp and run it separately?

**Comment by Israrulhaq190** [comment]
using this command: g++ run.cpp -o main

I compiled and below is the error output. 

```
/tmp/ccoaURC2.o: In function `GetImage(cv::Mat const&, float*)':
run.cpp:(.text+0x3c): undefined reference to `__android_log_print'
/tmp/ccoaURC2.o: In function `main':
run.cpp:(.text+0x420): undefined reference to `cv::imread(cv::String const&, int)'
run.cpp:(.text+0x6ca): undefined reference to `__android_log_print'
/tmp/ccoaURC2.o: In function `cv::String::String(char const*)':
run.cpp:(.text._ZN2cv6StringC2EPKc[_ZN2cv6StringC5EPKc]+0x4d): undefined reference to `cv::String::allocate(unsigned long)'
/tmp/ccoaURC2.o: In function `cv::String::~String()':
run.cpp:(.text._ZN2cv6StringD2Ev[_ZN2cv6StringD5Ev]+0x14): undefined reference to `cv::String::deallocate()'
/tmp/ccoaURC2.o: In function `cv::Mat::Mat(cv::Mat const&)':
run.cpp:(.text._ZN2cv3MatC2ERKS0_[_ZN2cv3MatC5ERKS0_]+0x183): undefined reference to `cv::Mat::copySize(cv::Mat const&)'
/tmp/ccoaURC2.o: In function `cv::Mat::~Mat()':
run.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x39): undefined reference to `cv::fastFree(void*)'
/tmp/ccoaURC2.o: In function `cv::Mat::release()':
run.cpp:(.text._ZN2cv3Mat7releaseEv[_ZN2cv3Mat7releaseEv]+0x4b): undefined reference to `cv::Mat::deallocate()'
/tmp/ccoaURC2.o: In function `cv::Mat::operator()(cv::Rect_<int> const&) const':
run.cpp:(.text._ZNK2cv3MatclERKNS_5Rect_IiEE[_ZNK2cv3MatclERKNS_5Rect_IiEE]+0x27): undefined reference to `cv::Mat::Mat(cv::Mat const&, cv::Rect_<int> const&)'
/tmp/ccoaURC2.o: In function `cv::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
run.cpp:(.text._ZN2cv6StringC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN2cv6StringC5ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x69): undefined reference to `cv::String::allocate(unsigned long)'
/tmp/ccoaURC2.o: In function `Predictor::init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
run.cpp:(.text._ZN9Predictor4initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_S7_[_ZN9Predictor4initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_S7_]+0x2c5): undefined reference to `MXPredCreate'
run.cpp:(.text._ZN9Predictor4initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_S7_[_ZN9Predictor4initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_S7_]+0x2fb): undefined reference to `cv::text::loadClassifierNM1(cv::String const&)'
run.cpp:(.text._ZN9Predictor4initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_S7_[_ZN9Predictor4initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_S7_]+0x33b): undefined reference to `cv::text::createERFilterNM1(cv::Ptr<cv::text::ERFilter::Callback> const&, int, float, float, float, bool, float)'
/tmp/ccoaURC2.o: In function `Predictor::get_text_region(cv::Mat const&)':
run.cpp:(.text._ZN9Predictor15get_text_regionERKN2cv3MatE[_ZN9Predictor15get_text_regionERKN2cv3MatE]+0x8f): undefined reference to `cv::text::computeNMChannels(cv::_InputArray const&, cv::_OutputArray const&, int)'
run.cpp:(.text._ZN9Predictor15get_text_regionERKN2cv3MatE[_ZN9Predictor15get_text_regionERKN2cv3MatE]+0x140): undefined reference to `cv::operator-(cv::Scalar_<double> const&, cv::Mat const&)'
run.cpp:(.text._ZN9Predictor15get_text_regionERKN2cv3MatE[_ZN9Predictor15get_text_regionERKN2cv3MatE]+0x34f): undefined reference to `cv::text::erGrouping(cv::_InputArray const&, cv::_InputArray const&, std::vector<std::vector<cv::text::ERStat, std::allocator<cv::text::ERStat> >, std::allocator<std::vector<cv::text::ERStat, std::allocator<cv::text::ERStat> > > >&, std::vector<std::vector<cv::Vec<int, 2>, std::allocator<cv::Vec<int, 2> > >, std::allocator<std::vector<cv::Vec<int, 2>, std::allocator<cv::Vec<int, 2> > > > >&, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, float)'
run.cpp:(.text._ZN9Predictor15get_text_regionERKN2cv3MatE[_ZN9Predictor15get_text_regionERKN2cv3MatE]+0x3d0): undefined reference to `__android_log_print'
/tmp/ccoaURC2.o: In function `Predictor::predict[abi:cxx11](cv::Mat const&)':
run.cpp:(.text._ZN9Predictor7predictB5cxx11ERKN2cv3MatE[_ZN9Predictor7predictB5cxx11ERKN2cv3MatE]+0xdc): undefined reference to `cv::resize(cv::_InputArray const&, cv::_OutputArray const&, cv::Size_<int>, double, double, int)'
run.cpp:(.text._ZN9Predictor7predictB5cxx11ERKN2cv3MatE[_ZN9Predictor7predictB5cxx11ERKN2cv3MatE]+0x15b): undefined reference to `cv::cvtColor(cv::_InputArray const&, cv::_OutputArray const&, int, int)'
run.cpp:(.text._ZN9Predictor7predictB5cxx11ERKN2cv3MatE[_ZN9Predictor7predictB5cxx11ERKN2cv3MatE]+0x1a7): undefined reference to `__android_log_print'
run.cpp:(.text._ZN9Predictor7predictB5cxx11ERKN2cv3MatE[_ZN9Predictor7predictB5cxx11ERKN2cv3MatE]+0x25b): undefined reference to `MXPredSetInput'
run.cpp:(.text._ZN9Predictor7predictB5cxx11ERKN2cv3MatE[_ZN9Predictor7predictB5cxx11ERKN2cv3MatE]+0x26d): undefined reference to `MXPredForward'
run.cpp:(.text._ZN9Predictor7predictB5cxx11ERKN2cv3MatE[_ZN9Predictor7predictB5cxx11ERKN2cv3MatE]+0x2a8): undefined reference to `MXPredGetOutputShape'
run.cpp:(.text._ZN9Predictor7predictB5cxx11ERKN2cv3MatE[_ZN9Predictor7predictB5cxx11ERKN2cv3MatE]+0x376): undefined reference to `MXPredGetOutput'
run.cpp:(.text._ZN9Predictor7predictB5cxx11ERKN2cv3MatE[_ZN9Predictor7predictB5cxx11ERKN2cv3MatE]+0x5f2): undefined reference to `__android_log_print'
run.cpp:(.text._ZN9Predictor7predictB5cxx11ERKN2cv3MatE[_ZN9Predictor7predictB5cxx11ERKN2cv3MatE]+0x665): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
run.cpp:(.text._ZN9Predictor7predictB5cxx11ERKN2cv3MatE[_ZN9Predictor7predictB5cxx11ERKN2cv3MatE]+0x68d): undefined reference to `cv::waitKey(int)'
collect2: error: ld returned 1 exit status

```

**Comment by novioleo** [comment]
@Israrulhaq190 i think you need to learn how to compile correctly with g++.

**Comment by Israrulhaq190** [comment]
oops. did i compile wrong ? please point out the mistake.

**Comment by novioleo** [comment]
i think you can figure it out by yourself.

**Comment by Israrulhaq190** [comment]
yes. i was trying to figure it out.
is this the correct way

g++ run.cpp -L/usr/include/opencv2/ -lopencv_core -lopencv_imgcodecs -o Test

**Comment by Israrulhaq190** [comment]
> i think you can figure it out by yourself.

I tired to write the main function and it's running without errors but no output.

```
int main(int argc, char** argv) {

    BufferFile buf = BufferFile(argv[1]);
    std::vector<uchar> vec(buf.GetBuffer(), buf.GetBuffer() + buf.GetLength());
    
    try {
        predictor obj = predictor(argv[2],argv[3]);
        std::string result = obj.predict(vec);
        std::cout <<result<< std::endl;
    }catch(std::exception& e){
        std::cout<<e.what()<<std::endl;
    }
 return 0;
}
```

**Comment by novioleo** [comment]
the number of predictor parameter...


 
---Original---

**Comment by Israrulhaq190** [comment]
> the number of predictor parameter...
> […](#)
> ---Original--- From: "israrulhaq"<notifications@github.com&gt; Date: 2019/10/15 20:40:11 To: "novioleo/crnn.mxnet"<crnn.mxnet@noreply.github.com&gt;; Cc: "Comment"<comment@noreply.github.com&gt;;"Tao Luo"<744351893@qq.com&gt;; Subject: Re: [novioleo/crnn.mxnet] Test Image on C++ Invoker main.cpp file (#15) i think you can figure it out by yourself. I tired to write the main function and it's running without errors but no output. int main(int argc, char** argv) { BufferFile buf = BufferFile(argv[1]); std::vector<uchar&gt; vec(buf.GetBuffer(), buf.GetBuffer() + buf.GetLength()); try { predictor obj = predictor(argv[2],argv[3]); std::string result = obj.predict(vec); std::cout <<result<< std::endl; }catch(std::exception&amp; e){ std::cout<<e.what()<<std::endl; } return 0; } — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes. Number of predictor parameters are two in main.cpp and predict function has only 1 parameter.

This is the results after running it.

```
test_image.jpg ... 17810 bytes
/home/israr/Pictures/crnn.mxnet/model/digit-symbol.json ... 275686 bytes
/home/israr/Pictures/crnn.mxnet/model/digit-0000.params ... 3722250 bytes
[18:02:16] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.11.0. Attempting to upgrade...
[18:02:16] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
[18:02:16] src/executor/graph_executor.cc:2014: Subgraph backend MKLDNN is activated.
Segmentation fault (core dumped)

```

**Comment by novioleo** [comment]
use gdb to debug...


 
---Original---

**Comment by Israrulhaq190** [comment]
I changed the value of buffer length in second argument as you can see currently it's 10. it shows output but wrong results. when i run the same file multiple time it shows me different results(even in different length).

```
int main(int argc, char** argv) {

    BufferFile buf = BufferFile(argv[1]);
    const std::vector<uchar> vec(buf.GetBuffer(), buf.GetBuffer() + 10);
    
    try {
        predictor obj = predictor(argv[2],argv[3]);
        std::string result = obj.predict(vec);
        std::cout <<result<< std::endl;
    }catch(std::exception& e){
        std::cout<<e.what()<<std::endl;
    }
 return 0;
}
```

**Comment by Israrulhaq190** [comment]
could you add the readme that how to run the main.cpp separately as you mentioned you will add soon.

**Comment by novioleo** [comment]
i have forgot left readme these days...


 
---Original---

**Comment by Israrulhaq190** [comment]
ok
