### ISSUE TITLE
ADD TEXT LOCALTION

### ISSUE THREAD

**Issue by novioleo** [novioleo/crnn.mxnet#6]
i use the algorithm from opencv_contrib to location the text(temporary)，to detect the character area.this algorithm is suit for non-chinese text.i'll replace it with other simpler algorithm ,so that the mobile device can detect the text area much more efficient.

**Comment by novioleo** [comment]
I've been tried the following methods:
1.CTPN-----the model is so big and the train process is private and the speed is unsatisfactory
2.text-line ---- the model is so big
3. seglink ----- the speed is unsatisfactory
4.Textboxes ---- may be the choice.In order to speed up the network,i'd like to change the SSD architecture:change the convolution layer to mobilenet.

IF YOU HAVE OTHER IDEA,PLEASE LEFT IT.

**Comment by pribadihcr** [comment]
@novioleo,

had text detector implemented yet?

**Comment by novioleo** [comment]
@pribadihcr EAST~
but i havn't push it~~~
